# app_config.yml
app_name: BACHUETECH AI
version: v0.1.0
environment: devNone

empty:
dev:
  api_path: /ai/api/
  end_points:
    - id: chat
      path: /chat
devNone:
  api_path: /none/api/
  end_points:
    - id: chat
      path: /chat      
jeremy_dev:
  agent:
    host: localhost
    port: 23332
    secure: false
    end_point: /ai/api/chat
  files_app_dir: site
  app_path: /jeremy
  api_path: /ai/api/
  end_points:
    - id: chat
      path: /chat
    - id: prompt
      path: /prompt
    - id: models
      path: /models